name: visit_tracker
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  form_builder: ^1.0.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
 


flutter:

 
  uses-material-design: true

 
